### ISSUE TITLE
[ 8.1.a ] As a user, I want login with email and password, to allow users personal authentication.

### ISSUE THREAD

**Issue by iiinaD** [ITU-BDSA2024-GROUP14/Chirp#132]
### Acceptance criteria:

- [x] Add identity to our solution
- [x] Make identity work with our solution so users can register and login
- [x] Create two users as specified in the description.
- [x] #147

### Description:
Section 23.4 in the book explains how to add identity to existing Razor page.

### References:

- [lecture notes](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_08/README_PROJECT.md#1a-aspnet-core-identity)
- [ASP.CORE Indentity documentation](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=netcore-cli)

**Comment by JonathanVil** [comment]
The test acceptance criteria has been moved to a separate issue
