### ISSUE TITLE
[ 12.1.a ] As a user, I want to be able to access the information that the application stores about me , so i know they follow the GDPR.

### ISSUE THREAD

**Issue by iiinaD** [ITU-BDSA2024-GROUP14/Chirp#203]
### Acceptance criteria:

- [x] add link in top navigation bar, between the link to public timeline and logout. The link should be written as "about me" and should only appear if the user is authenticated.
- [x] Make sure the page lists: name, email, links to other users that the logged in user follows and all the logged in users cheeps
- [x] In the about me section make it possible to see all information about the user. This could be things like the name, email, links to other users, that the user is following.
- [ ] _optional_ Make it possible to download the information that is displayed on the page
- [x] #210

### References:

- [lecture_notes](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_12/README_PROJECT.md#add-feature-user-information-page)

**Comment by Oliverst8** [comment]
Closed since pull reqeust https://github.com/ITU-BDSA2024-GROUP14/Chirp/issues/210 merged all the remaining functionality into main
