### ISSUE TITLE
In order to streamline the development process, and make sure everyone has the same expectations, as developers, I can create a group contract

### ISSUE THREAD

**Issue by AugustBugge** [ITU-BDSA2024-GROUP14/Chirp#3]
**Description**
We currently haven't made sure we are all on the same page as how we want to work on this project.

**Acceptance criteria**
We have a written group contract on Overleaf, that discusses how we want to work on the project, and our expectations, that every group member has signed.

**Comment by Obrinch** [comment]
💯
