### ISSUE TITLE
As a developer, I want to fix the bug not attaching release files on tag pushes, to allow user to download the newest release

### ISSUE THREAD

**Issue by Oliverst8** [ITU-BDSA2024-GROUP14/Chirp#60]

**Comment by Kami-prog** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
