### ISSUE TITLE
[ 5.2.b ] As a developer I want to not have to manually deploy our app.

### ISSUE THREAD

**Issue by AugustBugge** [ITU-BDSA2024-GROUP14/Chirp#76]
[Link to page](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_05/README_PROJECT.md#2b-add-automatic-deployment-of-razor-page-app)

Acceptance Criteria:
- [x] Modify our automatic deployment workflow to automatically deploy the razor Page Chirp! to azure.
- [x] Modify build test to build the razor page
- [x] Modify release workflow to release the razor page
- [x] Make sure the website is available at https://bdsagroup<no>chirprazor.azurewebsites.net/

**Comment by Oliverst8** [comment]
Reopened issue from automatic closing, since we are still waiting on response on what do with the fourth acceptance criteria
