### ISSUE TITLE
[ 6.1.c  ] As a Developer, I want use DTOs between database ang program, so that we avoid having to write sql queries.

### ISSUE THREAD

**Issue by Oliverst8** [ITU-BDSA2024-GROUP14/Chirp#91]
### Acceptance criteria:
- [x] Uses only predefined types in the DTOs
- [x] Create a message DTO (Class)
- [x] Create a user DTO (Class)

### Refrences:

- [Lecture notes](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_06/README_PROJECT.md#1c-data-transfer-objects-dtos)

**Comment by iiinaD** [comment]
Er ret sikker på vi ikke behøves  en user DTO da vi lige nu kun skal kunne sende queries til databasen om cheeps og ikke users.

**Comment by Oliverst8** [comment]
Need to add user DTO
